# Generated by Django 5.1.1 on 2024-10-04 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrEvento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('organizador', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estadoEvento', models.CharField(default='Pendiente', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventosya.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventosya.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
